# Generated by Django 4.0.3 on 2022-04-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
